### ISSUE TITLE
npm run build-css fails

### ISSUE THREAD

**Issue by Mhbuur** [patternfly/patternfly-react-demo-app#30] opened 2018-06-20 09:35 UTC
I'm trying to build the demo on Windows. I had to sort out some basic issues with cp command and sass on Windows 64 bit (see my comment here for details: https://github.com/patternfly/patternfly-react-demo-app/issues/23).

But I'm stuck with some Sass compile error:

`  "status": 1,
  "file": "c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss",
  "line": 11,
  "column": 1,
  "message": "File to import not found or unreadable: patternfly.\nParent style sheet: c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss",
  "formatted": "Error: File to import not found or unreadable: patternfly.\n       Parent style shee
t: c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss\n        on line 11 of src/A
pp.scss\n>> @import 'patternfly';\n   ^\n"`

and the relevant code in App.scss is an `@import 'patternfly';` statement. Patternfly module is installed. I've tried a ton of different path variations, but all ends up with the same result.

What is going on here?

**Comment by Mhbuur** [comment] 2018-06-20 11:49
I realized this is the variable issue @dmiller9911 mentions in https://github.com/patternfly/patternfly-react-demo-app/issues/23. I found a solution and will add that there. This one can be closed.

**Comment by jeff-phillips-18** [comment] 2018-06-20 12:51
Duplicate of #23

**Closed as completed by jeff-phillips-18** 2018-06-20 12:51 UTC

**Comment by Mhbuur** [comment] 2018-08-09 10:39
regarding failing import statements in App.scss, see https://github.com/patternfly/patternfly-react-demo-app/issues/37
